jenkins:
  agentProtocols:
    - 'JNLP4-connect'
    - 'Ping'
  slaveAgentPort: 50000
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true

  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: true

  numExecutors: ${JENKINS_MASTER_EXECUTORS}
  quietPeriod: ${JENKINS_QUIET_PERIOD}
  scmCheckoutRetryCount: ${JENKINS_SCM_RETRY_COUNT}
  labelString: master
  mode: EXCLUSIVE

unclassified:
  location:
    adminAddress: ${JENKINS_ADMIN}
    url: ${JENKINS_URL}

  gitHubPluginConfig:
    hookSecretConfigs:
      - credentialsId: ${GITHUB_WEBHOOK_CRED_ID}

  slackNotifier:
    teamDomain: ${SLACK_WORKSPACE}
    room: ${SLACK_DEFAULT_CHANNEL}
    tokenCredentialId: ${SLACK_CRED_ID}
    botUser: ${SLACK_BOT_USER}

  timestamper:
    allPipelines: true
