name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

  # Run a weekly update to get the latest packages
  workflow_dispatch:
  schedule:
    - cron: 0 9 * * *

permissions:
  contents: read
  packages: write

jobs:

  build_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker meta details
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{github.repository}}
          tags: |
            type=edge,branch=master
            type=semver,pattern={{version}}
            type=schedule,pattern=nightly
            type=schedule,pattern=schedule-{{date 'YYYYMMDD'}}
            type=sha

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Push Release
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'scheduled' || startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
